implementing issue#15
WSUCEG-7140/minecraftclone pull request #45
Opened 2023-06-29 14:24 UTC by kruslin2

Updated testing code

2023-06-30 02:58 UTC, cleancoder1016 requested changes

2023-06-30 02:58 UTC, cleancoder1016 commented on plant.py
> +        self.vertex_positions = [
there are no comments to the code after line 45. please add comments to increase to code readability.

2023-06-30 02:58 UTC, cleancoder1016 commented on snow.py
> +
there are no comments to the code after line 66. please add comments to increase to code readability.

2023-06-30 02:58 UTC, cleancoder1016 commented on util.py
> +
there are no comments to the code after line 45. please add comments to increase to code readability.

2023-07-03 16:15 UTC, cleancoder1016 commented
please merge this branch
@kruslin2

2023-07-03 17:22 UTC, atanake147 commented on plant.py
> +        self.vertex_positions = [
Comments added

2023-07-03 17:22 UTC, atanake147 commented on snow.py
> +
Comments added

2023-07-03 17:36 UTC, kruslin2 commented on snow.py
> +
Comments were added

2023-07-03 17:36 UTC, kruslin2 commented on util.py
> +
Comments were added

2023-07-03 17:41 UTC, cleancoder1016 approved these changes

2023-07-03 17:43 UTC, merged

2023-07-08 21:37 UTC, kruslin2 commented
[Coverage for door.py_ 100%.pdf](https://github.com/WSUCEG-7140/minecraftclone/files/11992441/Coverage.for.door.py_.100.pdf)
[Coverage for fire.py_ 100%.pdf](https://github.com/WSUCEG-7140/minecraftc
[Coverage for plant.py_ 100%.pdf](https://github.com/WSUCEG-7140/minecraftclone/file
[Coverage for snow.py_ 100%.pdf](https://github.com/WSUCEG-7140/minecraftclone/files/11992456/Coverage.for.snow.py_.100.pdf)
s/11992452/Coverage.for.plant.py_.100.pdf)
lone/files/11992445/Coverage.for.fire.py_.100.pdf)

2023-07-08 21:39 UTC, kruslin2 commented
[Coverage for door.py_ 100%.pdf](https://github.com/WSUCEG-7140/minecraftclone/files/11992457/Coverage.for.door.py_.100.pdf)
[Coverage for fire.py_ 100%.pdf](https://github.com/WSUCEG-7140/minecraftclone/files/11992458/Coverage.for.fire.py_.100.pdf)

2023-07-08 21:39 UTC, kruslin2 commented
[Coverage for plant.py_ 100%.pdf](https://github.com/WSUCEG-7140/minecraftclone/files/11992460/Coverage.for.plant.py_.100.pdf)
[Coverage for snow.py_ 100%.pdf](https://github.com/WSUCEG-7140/minecraftclone/files/11992461/Coverage.for.snow.py_.100.pdf)